# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Mahdiyar
tagline:          'Seyyed Mahdiyar Zerehpoush'
description:      'My Personal Blog :)'
url:              https://mahdiyar.me
baseurl:          /

author:
  name:           'Seyyed Mahdiyar Zerehpoush'
  url:            https://twitter.com/SeyyedMahdiyar

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/smzerehpoush
